blank_issues_enabled: true
contact_links:
  - name: Package build issue reports have moved
    url: https://github.com/spack/spack-packages/issues/new?template=build_error.yml
    about: Please report installation issues in the spack/spack-packages repository.
